"""Turns a decision plus its cited guidance into validated, safety-scanned advice.

Generation is optional and strictly additive: a local language model expands the
same cited guidance text every client can already read at
``GET /api/v1/guidance/{decision}`` into a longer explanation and an action plan.
It is never consulted for the decision itself and cannot override, contradict or
replace :mod:`shrimp_screening.guidance.store`.

Two independent safety layers apply, and both must hold:

1. **The prompt** (:mod:`shrimp_screening.llm.prompts`) instructs the model never
   to name a drug, a dose or a diagnosis, and to ground its answer only in the
   supplied guidance text.
2. **The output scan**, using the very same
   :func:`shrimp_screening.guidance.lexicon.scan` the guidance corpus itself must
   pass at load time. A prompt is a request, not a guarantee; the scan is the
   actual gate, and it runs over every generated string before any of them can
   reach a response.

A local model can also simply fail to produce usable JSON, or Ollama can be
unreachable. Both are :class:`AdviceGenerationError`, which the route turns into
a ``503`` rather than serving a partial, malformed or unsafe answer.
"""

from __future__ import annotations

import json
from dataclasses import dataclass

from shrimp_screening.contracts.enums import Decision
from shrimp_screening.guidance.lexicon import scan
from shrimp_screening.guidance.store import GuidanceItem
from shrimp_screening.llm.client import OllamaClient, OllamaError
from shrimp_screening.llm.prompts import SYSTEM_PROMPT, build_prompt
from shrimp_screening.settings import MAX_ADVICE_ITEMS_PER_LIST

#: Disclosed on every generated response so a client cannot render the advice
#: without also rendering the fact that it is unreviewed AI output.
REVIEW_STATUS = "AI_GENERATED_NOT_REVIEWED"
REVIEW_NOTE = (
    "This explanation and action list were generated by a local language model from "
    "the cited guidance above. It has not been reviewed by a qualified aquatic-animal "
    "health professional, may omit relevant considerations, and is not veterinary, "
    "medical or regulatory advice. It will never name a medication, chemical or dose."
)

_REQUIRED_LIST_FIELDS = ("immediate_actions", "prevention_actions")


class AdviceGenerationError(RuntimeError):
    """Advice could not be generated, or the model's answer was unsafe to serve."""


@dataclass(frozen=True, slots=True)
class AdviceContent:
    """The generated fields, already validated and scanned clean."""

    summary: str
    immediate_actions: tuple[str, ...]
    prevention_actions: tuple[str, ...]
    additional_considerations: tuple[str, ...]


def _string_list(payload: dict[str, object], key: str, *, required: bool) -> tuple[str, ...]:
    value = payload.get(key)
    if value is None and not required:
        return ()
    if not isinstance(value, list) or (required and not value):
        raise AdviceGenerationError(f"the model's response had no usable {key!r}")
    items = tuple(str(item).strip() for item in value if str(item).strip())
    if required and not items:
        raise AdviceGenerationError(f"the model's response had no usable {key!r}")
    return items[:MAX_ADVICE_ITEMS_PER_LIST]


def _parse(raw: str) -> AdviceContent:
    try:
        payload = json.loads(raw)
    except json.JSONDecodeError as exc:
        raise AdviceGenerationError("the model did not return valid JSON") from exc
    if not isinstance(payload, dict):
        raise AdviceGenerationError("the model's JSON response was not an object")

    summary = str(payload.get("summary", "")).strip()
    if not summary:
        raise AdviceGenerationError("the model's response had no usable summary")

    return AdviceContent(
        summary=summary,
        immediate_actions=_string_list(payload, "immediate_actions", required=True),
        prevention_actions=_string_list(payload, "prevention_actions", required=True),
        additional_considerations=_string_list(
            payload, "additional_considerations", required=False
        ),
    )


def _assert_safe(content: AdviceContent) -> None:
    combined = "\n".join(
        (
            content.summary,
            *content.immediate_actions,
            *content.prevention_actions,
            *content.additional_considerations,
        )
    )
    if scan(combined):
        # The specific violation is not echoed to the client: it is model output,
        # not a fixed detail string, and this module's own rule against leaking
        # unreviewed text applies to the failure path too. It is fully visible in
        # the server log via the caller's request id.
        raise AdviceGenerationError(
            "the model's response made a claim this system is not entitled to make"
        )


async def generate_advice(
    client: OllamaClient,
    *,
    decision: Decision,
    guidance_item: GuidanceItem,
) -> AdviceContent:
    """Call the local model and return validated, safety-scanned content."""
    prompt = build_prompt(decision, guidance_item)
    try:
        raw = await client.generate(system=SYSTEM_PROMPT, prompt=prompt)
    except OllamaError as exc:
        raise AdviceGenerationError(str(exc)) from exc

    content = _parse(raw)
    _assert_safe(content)
    return content
